# Generated by Django 6.0.1 on 2026-02-27 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable internal key (e.g. "web-design").', max_length=64, unique=True)),
                ('tr_name', models.CharField(max_length=200)),
                ('tr_base_path', models.SlugField(help_text='Base path after /tr/ (e.g. "web-tasarim").', max_length=120)),
                ('en_name', models.CharField(max_length=200)),
                ('en_base_path', models.SlugField(help_text='Base path after /en/ (e.g. "web-design").', max_length=120)),
            ],
            options={
                'verbose_name': 'SEO Service',
                'verbose_name_plural': 'SEO Services',
            },
        ),
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('tr', 'Turkish'), ('en', 'English')], max_length=2)),
                ('page_type', models.CharField(choices=[('pillar', 'Pillar'), ('pricing', 'Pricing'), ('guide', 'Guide'), ('cluster', 'Cluster'), ('quote', 'Quote')], max_length=16)),
                ('slug', models.SlugField(blank=True, default='', max_length=160)),
                ('title', models.CharField(help_text='H1', max_length=300)),
                ('meta_title', models.CharField(blank=True, max_length=300)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=300)),
                ('og_description', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('faq_json', models.JSONField(blank=True, default=list, help_text='List of {"question": "...", "answer": "..."} objects.')),
                ('is_indexable', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_pages', to='seo_pages.service')),
            ],
            options={
                'verbose_name': 'SEO Page',
                'verbose_name_plural': 'SEO Pages',
                'indexes': [models.Index(fields=['language', 'service', 'page_type', 'slug'], name='seo_pages_s_languag_d84e8b_idx'), models.Index(fields=['language', 'is_indexable', 'published_at'], name='seo_pages_s_languag_d1f7ab_idx')],
                'unique_together': {('language', 'service', 'page_type', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='InternalLinkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('tr', 'Turkish'), ('en', 'English')], max_length=2)),
                ('from_page_type', models.CharField(choices=[('pillar', 'Pillar'), ('pricing', 'Pricing'), ('guide', 'Guide'), ('cluster', 'Cluster'), ('quote', 'Quote')], max_length=16)),
                ('to_page_type', models.CharField(choices=[('pillar', 'Pillar'), ('pricing', 'Pricing'), ('guide', 'Guide'), ('cluster', 'Cluster'), ('quote', 'Quote')], max_length=16)),
                ('anchor_text', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_link_rules', to='seo_pages.service')),
            ],
            options={
                'verbose_name': 'Internal Link Rule',
                'verbose_name_plural': 'Internal Link Rules',
                'indexes': [models.Index(fields=['language', 'service', 'from_page_type'], name='seo_pages_i_languag_fa8f1c_idx')],
            },
        ),
    ]
