# Generated by GPT for service silo seed

from __future__ import annotations

from django.db import migrations
from django.utils import timezone


def _title_from_slug(slug: str) -> str:
    if not slug:
        return ""
    return slug.replace("-", " ").replace("  ", " ").title()


def seed(apps, schema_editor):
    Service = apps.get_model("seo_pages", "Service")
    SeoPage = apps.get_model("seo_pages", "SeoPage")

    now = timezone.now()

    services = [
        {
            "key": "web-design",
            "tr_name": "Web Tasarım",
            "tr_base_path": "web-tasarim",
            "en_name": "Web Design",
            "en_base_path": "web-design",
            "tr_clusters": [
                "kurumsal-web-sitesi",
                "kurumsal-web-sitesi-yaptirmak",
                "istanbul",
                "ozel-yazilim-web-sitesi",
                "django-web-gelistirme",
                "profesyonel-web-tasarim",
                "web-tasarim-sirketi",
                "web-tasarim-freelancer",
                "web-developer-istanbul",
                "ozel-yazilim-vs-hazir-site",
                "django-vs-php",
                "ajans-mi-freelancer-mi",
            ],
            "en_clusters": [
                "web-design-services",
                "web-design-agency",
                "web-development-company",
                "corporate-website-development",
                "custom-web-development",
                "django-web-development",
                "hire-web-developer",
                "web-design-company-istanbul",
                "what-is-web-design",
                "how-to-build-a-website",
                "custom-website-vs-template",
                "django-vs-php",
            ],
        },
        {
            "key": "mobile-app-development",
            "tr_name": "Mobil Uygulama Geliştirme",
            "tr_base_path": "mobil-uygulama-gelistirme",
            "en_name": "Mobile App Development",
            "en_base_path": "mobile-app-development",
            "tr_clusters": [
                "react-native",
                "android",
                "ios",
                "ozel-mobil-uygulama",
                "istanbul",
                "mobil-uygulama-nedir",
                "mobil-uygulama-nasil-yapilir",
                "mobil-uygulama-freelancer",
                "react-native-vs-native",
                "android-vs-ios",
            ],
            "en_clusters": [
                "react-native-app-development",
                "android-app-development",
                "ios-app-development",
                "custom-mobile-app-development",
                "mobile-app-development-company",
                "what-is-mobile-app-development",
                "hire-mobile-app-developer",
                "react-native-vs-native",
                "cross-platform-vs-native",
                "mobile-app-development-cost",
            ],
        },
        {
            "key": "ecommerce-development",
            "tr_name": "E‑Ticaret Geliştirme",
            "tr_base_path": "e-ticaret-gelistirme",
            "en_name": "Ecommerce Development",
            "en_base_path": "ecommerce-development",
            "tr_clusters": [
                "e-ticaret-sitesi",
                "e-ticaret-yazilimi",
                "ozel-e-ticaret-yazilimi",
                "b2b",
                "b2c",
                "e-ticaret-yazilim-firmasi",
                "e-ticaret-sitesi-yaptirmak",
                "e-ticaret-nedir",
                "e-ticaret-sitesi-nasil-kurulur",
                "ozel-yazilim-vs-hazir-altyapi",
            ],
            "en_clusters": [
                "custom-ecommerce-development",
                "ecommerce-development-company",
                "ecommerce-platform-development",
                "b2b-ecommerce-development",
                "b2c-ecommerce-website",
                "what-is-ecommerce",
                "ecommerce-website-guide",
                "ecommerce-website-cost",
                "ecommerce-pricing",
                "custom-vs-template-ecommerce",
            ],
        },
        {
            "key": "seo-services",
            "tr_name": "SEO Hizmetleri",
            "tr_base_path": "seo-hizmetleri",
            "en_name": "SEO Services",
            "en_base_path": "seo-services",
            "tr_clusters": [
                "seo-danismanligi",
                "teknik-seo",
                "on-page-seo",
                "seo-analizi",
                "istanbul-seo-ajansi",
                "seo-uzmani",
                "seo-nedir",
                "seo-nasil-yapilir",
                "seo-uyumlu-web-sitesi",
                "ajans-mi-freelancer-mi",
            ],
            "en_clusters": [
                "technical-seo-services",
                "on-page-seo-services",
                "seo-consultancy",
                "seo-pricing",
                "seo-cost",
                "what-is-seo",
                "how-seo-works",
                "hire-seo-expert",
                "seo-audit",
                "seo-for-django-sites",
            ],
        },
        {
            "key": "hosting-domain",
            "tr_name": "Hosting & Domain",
            "tr_base_path": "hosting-domain",
            "en_name": "Hosting & Domain",
            "en_base_path": "hosting-domain",
            "tr_clusters": [
                "hosting-hizmeti",
                "vps-hosting",
                "ozel-sunucu-kiralama",
                "bulut-sunucu",
                "django-deployment",
                "domain-satin-al",
                "ssl-sertifikasi",
                "linux-sunucu-kurulumu",
                "web-hosting-fiyatlari",
                "vps-fiyatlari",
            ],
            "en_clusters": [
                "web-hosting-services",
                "vps-hosting",
                "dedicated-server-hosting",
                "cloud-hosting",
                "django-hosting",
                "domain-registration",
                "ssl-certificate",
                "linux-server-setup",
                "web-hosting-pricing",
                "vps-hosting-cost",
            ],
        },
        {
            "key": "ui-ux-design",
            "tr_name": "UI/UX Tasarım",
            "tr_base_path": "ui-ux-tasarim",
            "en_name": "UI/UX Design",
            "en_base_path": "ui-ux-design",
            "tr_clusters": [
                "ui-ux-nedir",
                "kullanici-deneyimi-tasarimi",
                "kullanici-arayuzu-tasarimi",
                "ui-ux-tasarim-hizmeti",
                "mobil-uygulama-arayuz-tasarimi",
                "ux-arastirmasi",
                "figma-tasarim",
                "wireframe-tasarimi",
                "prototype-tasarimi",
                "ui-ux-tasarim-fiyatlari",
            ],
            "en_clusters": [
                "ui-ux-design-services",
                "user-experience-design",
                "user-interface-design",
                "what-is-ui-ux",
                "figma-design",
                "wireframe-design",
                "prototype-design",
                "mobile-app-ui-design",
                "ui-ux-pricing",
                "ux-research",
            ],
        },
    ]

    # Upsert services (idempotent)
    svc_by_key = {}
    for s in services:
        obj, _created = Service.objects.update_or_create(
            key=s["key"],
            defaults={
                "tr_name": s["tr_name"],
                "tr_base_path": s["tr_base_path"],
                "en_name": s["en_name"],
                "en_base_path": s["en_base_path"],
            },
        )
        svc_by_key[s["key"]] = obj

    # Seed pages (idempotent per unique constraint)
    for s in services:
        svc = svc_by_key[s["key"]]

        for language in ("tr", "en"):
            base = s["tr_base_path"] if language == "tr" else s["en_base_path"]
            svc_name = s["tr_name"] if language == "tr" else s["en_name"]

            def upsert(page_type: str, slug: str, title: str):
                url = f"/{language}/{base}/" if not slug else f"/{language}/{base}/{slug}/"
                SeoPage.objects.update_or_create(
                    language=language,
                    service=svc,
                    page_type=page_type,
                    slug=slug,
                    defaults={
                        "title": title,
                        "meta_title": "",
                        "meta_description": "",
                        "canonical_url": url,
                        "og_title": "",
                        "og_description": "",
                        "content_html": "",
                        "faq_json": [],
                        "is_indexable": True,
                        "published_at": now,
                    },
                )

            # Core page types
            upsert("pillar", "", svc_name)
            upsert("pricing", "fiyatlar" if language == "tr" else "pricing", f"{svc_name} - {'Fiyatlar' if language=='tr' else 'Pricing'}")
            upsert("guide", "rehber" if language == "tr" else "guide", f"{svc_name} - {'Rehber' if language=='tr' else 'Guide'}")
            upsert("quote", "teklif-al" if language == "tr" else "get-quote", f"{svc_name} - {'Teklif Al' if language=='tr' else 'Get a Quote'}")

            # Clusters
            clusters = s["tr_clusters"] if language == "tr" else s["en_clusters"]
            for cslug in clusters:
                upsert("cluster", cslug, _title_from_slug(cslug))


def unseed(apps, schema_editor):
    Service = apps.get_model("seo_pages", "Service")
    SeoPage = apps.get_model("seo_pages", "SeoPage")

    keys = [
        "web-design",
        "mobile-app-development",
        "ecommerce-development",
        "seo-services",
        "hosting-domain",
        "ui-ux-design",
    ]
    pages = SeoPage.objects.filter(service__key__in=keys)
    pages.delete()
    Service.objects.filter(key__in=keys).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("seo_pages", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed, reverse_code=unseed),
    ]

