# Generated by Django 6.0.1 on 2026-02-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_pages', '0002_seed_service_silos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seopage',
            name='canonical_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
