# Generated by Django 6.0.1 on 2026-02-26 10:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsightSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('cid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('first_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
                ('consent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Insight Session',
                'verbose_name_plural': 'Insight Sessions',
                'db_table': 'insights_session',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='MetaAuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2048)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('h1_count', models.PositiveIntegerField(default=0)),
                ('canonical', models.URLField(blank=True, max_length=2048)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('resp_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('issues_json', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Meta Audit Result',
                'verbose_name_plural': 'Meta Audit Results',
                'db_table': 'insights_meta_audit_result',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='SerpSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('results_json', models.JSONField(default=dict)),
                ('our_domain_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SERP Snapshot',
                'verbose_name_plural': 'SERP Snapshots',
                'db_table': 'insights_serp_snapshot',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='GSCPageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('page', models.URLField(db_index=True, max_length=2048)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('position', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'GSC Page Stat',
                'verbose_name_plural': 'GSC Page Stats',
                'db_table': 'insights_gsc_page_stat',
                'ordering': ['-date', '-clicks'],
                'indexes': [models.Index(fields=['date', 'page'], name='insights_gs_date_d0b8d7_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'page'), name='insights_gsc_page_unique')],
            },
        ),
        migrations.CreateModel(
            name='GSCQueryPageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('query', models.CharField(db_index=True, max_length=500)),
                ('page', models.URLField(db_index=True, max_length=2048)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('position', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'GSC Query+Page Stat',
                'verbose_name_plural': 'GSC Query+Page Stats',
                'db_table': 'insights_gsc_query_page_stat',
                'ordering': ['-date', '-clicks'],
                'indexes': [models.Index(fields=['date', 'query'], name='insights_gs_date_91f105_idx'), models.Index(fields=['date', 'page'], name='insights_gs_date_d15692_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'query', 'page'), name='insights_gsc_qp_unique')],
            },
        ),
        migrations.CreateModel(
            name='InsightEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('page_view', 'Page View'), ('scroll_depth', 'Scroll Depth'), ('click', 'Click'), ('page_exit', 'Page Exit'), ('rage_click', 'Rage Click')], db_index=True, max_length=20)),
                ('url', models.URLField(blank=True, db_index=True, max_length=2048)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payload', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='insights.insightsession')),
            ],
            options={
                'verbose_name': 'Insight Event',
                'verbose_name_plural': 'Insight Events',
                'db_table': 'insights_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['type', 'occurred_at'], name='insights_ev_type_29d78d_idx'), models.Index(fields=['url', 'occurred_at'], name='insights_ev_url_777d4c_idx')],
            },
        ),
    ]
