# Generated by Django 6.0.1 on 2026-02-26 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('rule_key', models.CharField(db_index=True, max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('context_json', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Insight Alert',
                'verbose_name_plural': 'Insight Alerts',
                'db_table': 'insights_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('gsc_start_date', models.DateField(blank=True, null=True)),
                ('gsc_end_date', models.DateField(blank=True, null=True)),
                ('behavior_start_date', models.DateField(blank=True, null=True)),
                ('behavior_end_date', models.DateField(blank=True, null=True)),
                ('gsc_json', models.JSONField(default=dict)),
                ('behavior_json', models.JSONField(default=dict)),
                ('meta_issues_json', models.JSONField(default=dict)),
                ('opportunities_json', models.JSONField(default=list)),
                ('ux_issues_json', models.JSONField(default=list)),
                ('meta_issues_pages_json', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'SEO Health Snapshot',
                'verbose_name_plural': 'SEO Health Snapshots',
                'db_table': 'insights_seo_health_snapshot',
                'ordering': ['-snapshot_at'],
            },
        ),
    ]
