# Generated by Django 5.1.2 on 2026-01-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('role', models.CharField(choices=[('pm', 'Project Manager'), ('backend', 'Backend Developer'), ('frontend', 'Frontend Developer'), ('mobile', 'Mobile Developer'), ('uiux', 'UI/UX Designer'), ('qa', 'QA Engineer'), ('seo', 'SEO Specialist'), ('devops', 'DevOps Engineer'), ('other', 'Other')], default='other', max_length=50, verbose_name='نقش')),
                ('headline', models.CharField(blank=True, max_length=250, verbose_name='تیتر کوتاه')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='عکس')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('website_url', models.URLField(blank=True, verbose_name='Website')),
                ('skills', models.CharField(blank=True, max_length=500, verbose_name='مهارت\u200cها (با کاما جدا کنید)')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='سال تجربه')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'عضو تیم',
                'verbose_name_plural': 'اعضای تیم',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
