# Generated by Django 5.1.2 on 2026-01-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='سوال')),
                ('question_en', models.CharField(blank=True, max_length=500, verbose_name='سوال انگلیسی')),
                ('question_fa', models.CharField(blank=True, max_length=500, verbose_name='سوال فارسی')),
                ('question_ar', models.CharField(blank=True, max_length=500, verbose_name='سوال عربی')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('answer_en', models.TextField(blank=True, verbose_name='پاسخ انگلیسی')),
                ('answer_fa', models.TextField(blank=True, verbose_name='پاسخ فارسی')),
                ('answer_ar', models.TextField(blank=True, verbose_name='پاسخ عربی')),
                ('category', models.CharField(choices=[('general', 'عمومی'), ('services', 'خدمات'), ('pricing', 'قیمت\u200cگذاری'), ('technical', 'فنی'), ('support', 'پشتیبانی'), ('other', 'سایر')], default='general', max_length=50, verbose_name='دسته\u200cبندی')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='نام')),
                ('subscribed', models.BooleanField(default=True, verbose_name='فعال')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اشتراک')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو اشتراک')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
            ],
            options={
                'verbose_name': 'مشترک خبرنامه',
                'verbose_name_plural': 'مشترکین خبرنامه',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
