# Generated by Django 5.1.2 on 2026-01-26 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_faq_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان انگلیسی')),
                ('title_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان فارسی')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='عنوان عربی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_ar', models.TextField(blank=True, verbose_name='توضیحات عربی')),
                ('icon', models.CharField(default='fas fa-check-circle', max_length=100, verbose_name='آیکون')),
                ('step_number', models.IntegerField(verbose_name='شماره مرحله')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='مدت زمان (مثال: 1-2 روز)')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مرحله فرآیند',
                'verbose_name_plural': 'مراحل فرآیند',
                'ordering': ['order', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مهارت')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='نام انگلیسی')),
                ('name_fa', models.CharField(blank=True, max_length=100, verbose_name='نام فارسی')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='نام عربی')),
                ('icon', models.CharField(default='fas fa-code', max_length=100, verbose_name='آیکون')),
                ('percentage', models.IntegerField(default=0, verbose_name='درصد (0-100)')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('tools', 'Tools'), ('other', 'سایر')], default='other', max_length=50, verbose_name='دسته\u200cبندی')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان انگلیسی')),
                ('title_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان فارسی')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='عنوان عربی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_ar', models.TextField(blank=True, verbose_name='توضیحات عربی')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('icon', models.CharField(default='fas fa-calendar', max_length=100, verbose_name='آیکون')),
                ('event_type', models.CharField(choices=[('education', 'تحصیلات'), ('work', 'کار'), ('achievement', 'دستاورد'), ('certification', 'گواهینامه'), ('other', 'سایر')], default='other', max_length=50, verbose_name='نوع رویداد')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'رویداد Timeline',
                'verbose_name_plural': 'رویدادهای Timeline',
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان انگلیسی')),
                ('title_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان فارسی')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='عنوان عربی')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='نام مشتری')),
                ('client_industry', models.CharField(blank=True, max_length=200, verbose_name='صنعت')),
                ('challenge', models.TextField(verbose_name='چالش')),
                ('challenge_en', models.TextField(blank=True, verbose_name='چالش انگلیسی')),
                ('challenge_fa', models.TextField(blank=True, verbose_name='چالش فارسی')),
                ('challenge_ar', models.TextField(blank=True, verbose_name='چالش عربی')),
                ('solution', models.TextField(verbose_name='راه\u200cحل')),
                ('solution_en', models.TextField(blank=True, verbose_name='راه\u200cحل انگلیسی')),
                ('solution_fa', models.TextField(blank=True, verbose_name='راه\u200cحل فارسی')),
                ('solution_ar', models.TextField(blank=True, verbose_name='راه\u200cحل عربی')),
                ('results', models.TextField(verbose_name='نتایج')),
                ('results_en', models.TextField(blank=True, verbose_name='نتایج انگلیسی')),
                ('results_fa', models.TextField(blank=True, verbose_name='نتایج فارسی')),
                ('results_ar', models.TextField(blank=True, verbose_name='نتایج عربی')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='آمار (JSON)')),
                ('image_before', models.ImageField(blank=True, null=True, upload_to='case_studies/', verbose_name='تصویر قبل')),
                ('image_after', models.ImageField(blank=True, null=True, upload_to='case_studies/', verbose_name='تصویر بعد')),
                ('project_url', models.URLField(blank=True, verbose_name='لینک پروژه')),
                ('technologies', models.CharField(blank=True, max_length=500, verbose_name='تکنولوژی\u200cها (جدا شده با کاما)')),
                ('featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.project', verbose_name='پروژه مرتبط')),
            ],
            options={
                'verbose_name': 'مطالعه موردی',
                'verbose_name_plural': 'مطالعات موردی',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
