# Generated by Django 6.0.1 on 2026-02-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_add_package_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('services', 'Services'), ('pricing', 'Pricing'), ('technical', 'Technical'), ('support', 'Support'), ('other', 'Other')], default='general', max_length=50, verbose_name='دسته\u200cبندی'),
        ),
    ]
