# Generated by Django 6.0.1 on 2026-03-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_faq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='اسلاگ انگلیسی'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='برچسب\u200cها (با کاما)'),
        ),
    ]
