"""
Django settings for angraweb_project project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable in production, fallback for development only
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-h6uv1x%&)z%w^a(++ilj_$0ync968m1*zdr+%!b1$kk8$nti%q')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# django-ratelimit: پشت Nginx/پروکسی REMOTE_ADDR خالی است؛ IP را از هدر فورواردشده بگیر
RATELIMIT_IP_META_KEY = 'HTTP_X_FORWARDED_FOR'

# دامنهٔ canonical برای ایندکس و sitemap (بدون www، با https)
# در production حتماً تنظیم کن: CANONICAL_DOMAIN=https://angraweb.com
CANONICAL_DOMAIN = (os.environ.get('CANONICAL_DOMAIN') or os.environ.get('SITE_URL') or 'https://angraweb.com').strip().rstrip('/')

# Insights GSC sync: خوانده می‌شود توسط insights_sync_gsc و داشبورد SEO
INSIGHTS_GSC_SITE_URL = os.environ.get('INSIGHTS_GSC_SITE_URL', '')
INSIGHTS_GSC_CREDENTIALS_JSON = os.environ.get('INSIGHTS_GSC_CREDENTIALS_JSON', '')

# صفحه نگهداری (Bakım Modu): وقتی True باشد به جای سایت صفحه نگهداری به ترکی نمایش داده می‌شود.
# برای غیرفعال کردن: MAINTENANCE_MODE=False یا حذف این خط و استفاده از مقدار پیش‌فرض.
MAINTENANCE_MODE = os.environ.get('MAINTENANCE_MODE', 'False') == 'True'
MAINTENANCE_BYPASS_STAFF = True  # کاربران staff (ادمین) سایت عادی را ببینند


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'main',
    'insights',
    'seo_pages',
]

MIDDLEWARE = [
    'main.middleware.CanonicalRedirectMiddleware',  # www → non-www و یکسان‌سازی canonical
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'main.middleware.XRobotsTagMiddleware',  # noindex for admin/search/utility URLs
    'django.middleware.locale.LocaleMiddleware',
    'main.middleware.LanguageActivationMiddleware',  # اطمینان از activate شدن زبان از session/cookie و لود ترجمه‌ها
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'main.middleware.SessionExpiryMiddleware',  # انقضای خودکار session بعد از مدت زمان مشخص
    'main.middleware.MaintenanceMiddleware',  # صفحه نگهداری (Bakım Modu) وقتی MAINTENANCE_MODE=True
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'angraweb_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'insights.context_processors.insights_settings',
                'main.context_processors.static_version',
                'main.context_processors.canonical_url',
            ],
        },
    },
]

WSGI_APPLICATION = 'angraweb_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

_use_pg = os.environ.get('USE_POSTGRES', '').lower() in ('1', 'true', 'yes')
if _use_pg:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'angraweb_db'),
            'USER': os.environ.get('POSTGRES_USER', 'angraweb_user'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': 60,
            'OPTIONS': {'sslmode': 'prefer'} if os.environ.get('POSTGRES_SSL') else {},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

USE_I18N = True

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

LANGUAGES = [
    ('tr', 'Turkish'),
    ('en', 'English'),
]

# Language-prefixed URLs use both /tr/ and /en/ (prefix_default_language=True in i18n_patterns).
# Until LocaleMiddleware runs, use this key for session; set_language view also uses it.
LANGUAGE_SESSION_KEY = '_language'
LANGUAGE_COOKIE_NAME = 'django_language'

# اطمینان از ذخیره شدن session در هر درخواست
SESSION_SAVE_EVERY_REQUEST = True

# Session Expiry - انقضای خودکار session بعد از 2 ساعت (7200 ثانیه)
# اگر کاربر 2 ساعت غیرفعال باشد، خودکار logout می‌شود
SESSION_COOKIE_AGE = 7200  # 2 hours in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session تا زمانی که مرورگر بسته نشود یا expire نشود باقی می‌ماند

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
# Cache busting: env یا فایل static_version.txt (اسکریپت دپلوی آن را با date +%s پر می‌کند)
def _static_version():
    v = os.environ.get('STATIC_VERSION')
    if v:
        return v
    try:
        p = BASE_DIR / 'static_version.txt'
        if p.is_file():
            return p.read_text(encoding='utf-8').strip() or '1'
    except Exception:
        pass
    return '1'
STATIC_VERSION = _static_version()

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    # Keep original asset folders addressable via {% static 'certificates/...' %} etc.
    ('certificates', BASE_DIR / 'certificates'),
    ('photos', BASE_DIR / 'photos'),
    ('videos', BASE_DIR / 'videos'),
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URLs (use named URLs so i18n prefixes work correctly)
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'

# Email (SMTP) — business inbox info@angraweb.com
# Credentials from environment variables; use EMAIL_HOST_PASSWORD in production.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'mega.promail.com.tr')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'info@angraweb.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# Display name for outgoing mail
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Angraweb <info@angraweb.com>')
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', EMAIL_HOST_USER or 'info@angraweb.com')

# Business contact: notifications go to this inbox
CONTACT_PRIMARY_EMAIL = os.environ.get('CONTACT_PRIMARY_EMAIL', 'info@angraweb.com')
CONTACT_SECONDARY_EMAIL = os.environ.get('CONTACT_SECONDARY_EMAIL', '')
CONTACT_NOTIFICATION_EMAILS = [
    e.strip() for e in os.environ.get(
        'CONTACT_NOTIFICATION_EMAILS',
        CONTACT_PRIMARY_EMAIL or ''
    ).split(',') if e.strip()
]
if not CONTACT_NOTIFICATION_EMAILS and CONTACT_PRIMARY_EMAIL:
    CONTACT_NOTIFICATION_EMAILS = [CONTACT_PRIMARY_EMAIL]

# Security Settings for Production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'main': {
            'handlers': ['console', 'file'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)
